/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'

export function Cactus(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/cactus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.upperArm.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lowerArm.geometry}
        material={materials['Material.001']}
      />
    </group>
  )
}

export function BizonSkull(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/bizon-skull.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BizonSkull.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
}

export function Can(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/can.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['14025_Soda_Can_v3_l3'].geometry}
        material={materials['14025_Soda_Can']}
      />
    </group>
  )
}

useGLTF.preload('/can.glb')
useGLTF.preload('/bizon-skull.glb')
useGLTF.preload('/cactus.glb')
