/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import { forwardRef } from 'react'

export function Cactus(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/cactus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.upperArm.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lowerArm.geometry}
        material={materials['Material.001']}
      />
    </group>
  )
}

export function BizonSkull(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/bizon-skull.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BizonSkull.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
}

export function Can(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/can.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['14025_Soda_Can_v3_l3'].geometry}
        material={materials['14025_Soda_Can']}
      />
    </group>
  )
}

export const WindVane = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('models/Scarcity/wind.glb')
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve.geometry}
        material={materials['Material.003']}
      />
    </group>
  )
})

export function WoodSign(props) {
  const { nodes, materials } = useGLTF('models/Scarcity/sign.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sin_título.geometry}
        material={materials['Material.001']}
        position={[-2.93, 0, 1.589]}
      />
    </group>
  )
}

useGLTF.preload('models/Scarcity/sign.glb')
useGLTF.preload('models/Scarcity/wind.glb')
useGLTF.preload('models/Scarcity/can.glb')
useGLTF.preload('models/Scarcity/bizon-skull.glb')
useGLTF.preload('models/Scarcity/cactus.glb')
